#!/usr/bin/env python3

import time
from Quartz import CGEventCreateKeyboardEvent, CGEventPost, kCGHIDEventTap

# Keycode for Caps Lock on macOS
CAPS_LOCK = 57

def press_caps():
    event_down = CGEventCreateKeyboardEvent(None, CAPS_LOCK, True)
    event_up = CGEventCreateKeyboardEvent(None, CAPS_LOCK, False)
    CGEventPost(kCGHIDEventTap, event_down)
    CGEventPost(kCGHIDEventTap, event_up)

press_caps()
time.sleep(0.1)
press_caps()
