#!/usr/bin/env bash

set -e

MODE="$1"

if [[ "$MODE" != "on" && "$MODE" != "off" ]]; then
  echo "Usage: $0 [on|off]"
  exit 1
fi

current_space=$(yabai -m query --spaces --space | jq '.index')

if [[ "$MODE" == "on" ]]; then
  osascript -e 'tell application "LibreWolf" to quit'

  open -na "Chromium"
  sleep 1
  chromium_window_id=$(yabai -m query --windows | jq '.[] | select(.app == "Chromium") | .id' | tail -n1)
  yabai -m window "$chromium_window_id" --space 2
  yabai -m space --focus 2

  open -na "Slack"
  sleep 1
  slack_window_id=$(yabai -m query --windows | jq '.[] | select(.app == "Slack") | .id' | tail -n1)
  yabai -m window "$slack_window_id" --space 4
  yabai -m space --focus 4

  open -na "Twingate"
else
  osascript -e 'tell application "Chromium" to quit'
  osascript -e 'tell application "Slack" to quit'
  osascript -e 'tell application "Twingate" to quit'

  open -na "LibreWolf"
  sleep 1
  firefox_window_id=$(yabai -m query --windows | jq '.[] | select(.app == "LibreWolf") | .id' | tail -n1)
  yabai -m window "$firefox_window_id" --space 2
  yabai -m space --focus 2
fi

sleep 0.5
yabai -m space --focus "$current_space"

if [[ "$MODE" == "on" ]]; then
  ~/scripts/tmux-sessionizer.sh ~/projects/work/signus/signus-ui
else
  ~/scripts/tmux-sessionizer.sh ~
fi
